---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 16/05/23 12:39
---
local dbgLeleLib = require("lib/DbgLeleLib")
local characterPz = require("lib/CharacterPZ")
local perkFactoryPZ = require("lib/PerkFactoryPZ")
local isoPlayerPZ = require("lib/IsoPlayerPZ")
local modDataX = require("lib/ModDataX")
local characterLib = require("CharacterLib")

local function characterCharacteristics(CharacterObj, displayName)
    dbgLeleLib.printLine()

    for i, v in pairs(CharacterObj:getPerkDetails()) do
        print(displayName .. " >> " ..
            tostring(v:getPerk()) .. " - " ..
            tostring(v:getLevel()) .. " - " ..
            tostring(v:getXp()))
    end

    dbgLeleLib.printLine()
end

function displayCharacterDetails(character)
    local CharacterCreationObj = CharacterObj:new()
    CharacterCreationObj = getCharacterCreation(character)

    local CharacterProfessionObj = CharacterObj:new()
    CharacterProfessionObj = characterLib.getPerkProfession(character)

    local CharacterTraitsPerkObj = CharacterObj:new()
    CharacterTraitsPerkObj = characterLib.getTraitsPerk(character)

    local CharacterAllPerkObj = CharacterObj:new()
    CharacterAllPerkObj = characterLib.getAllPerks(character)

    local CharacterMaxSkillObj = CharacterObj:new()
    CharacterMaxSkillObj = initCharacter()

    characterCharacteristics(CharacterAllPerkObj, "All Perk")

    print("profession " .. CharacterProfessionObj:getProfession())
    characterCharacteristics(CharacterProfessionObj, "Profession Traits/Perk")
    characterCharacteristics(CharacterTraitsPerkObj, "Traits Perk")
    characterCharacteristics(CharacterMaxSkillObj, "Max Skill")

end

function checkModData()
    local characterMaxSkillModData = "characterMaxSkill"

    if modDataX.isExists(characterMaxSkillModData) then
        dbgLeleLib.checkTest(true, true, "Character MaxS kill ModData" )
    else
        dbgLeleLib.checkTest(false, true, "Character MaxS kill ModData" )
    end
end

-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
local function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > displayCharacterDetails \n")
         checkModData()
         displayCharacterDetails(character)
    end
end

---@param character IsoGameCharacter
local function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h > read \n")

    end
end

---@param character IsoGameCharacter
local function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j > delete \n")

    end
end

---@param character IsoGameCharacter
local function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k > delete \n")
        character:die()
    end
end

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    key34(character, key)
    --key35(character, key)
    --key36(character, key)
    key37(character, key)
end

---Delete modData when character is death -
---Triggered when a character or zombie is killed
---@param character IsoGameCharacter
local function OnCharacterDeath(character)
    if getPlayer():isDead() then
        print("Character killed")
        local characterMaxSkillModData = "characterMaxSkill"
        modDataX.remove(characterMaxSkillModData)
    else
        print("Zombi is killed")
    end
end

---Init Character -
---Triggered after the start of a new game, and after a saved game has been loaded.
local function OnGameStart()
    print("Triggered after the start of a new game, and after a saved game has been loaded.")
end

---Init Character -
---Triggered when a player is being created.
local function OnCreatePlayer(playerIndex, player)
    print("Triggered when a player is being created.")
end

--Events.OnCharacterDeath.Add(OnCharacterDeath)
--Events.OnGameStart.Add(OnGameStart)
--Events.OnCreatePlayer.Add(OnCreatePlayer)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)