---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 09/09/23 11:08
---

---@class ActivityCalendar

local ActivityCalendar = {}

local dataValidator = require("lib/DataValidator")

local month = {
    Jan = 1, Feb = 2, Mar = 3, Apr = 4, May = 5, Jun = 6,
    Jul = 7, Aug = 8, Sep = 9, Oct = 10, Nov = 11, Dec = 12
}

---@type int
local SECOND_IN_DAY = 86400

---@type double
local expectedDateInSecond

--- **Extract Date**
---@param date string
---@return int
local function extractDate(date)
    --- **Check if date is string**
    if not dataValidator.isString(date) then
        return
    end

    ---@type table
    local dateParts = {}

    --- **Extract date**
    for datePart in date:gmatch("%S+") do
        table.insert(dateParts, datePart)
    end

    --@type table
    local datePartsConverted = {
        ---@field number
        year = tonumber(dateParts[6]),
        ---@field number
        month = month[dateParts[2]],
        ---@field number
        day = tonumber(dateParts[3]),
        ---@field number
        hour = 0,
        ---@field number
        min = 0,
        ---@field number
        sec = 0
    }

    return os.time(datePartsConverted)
end

--- **Get Seconds From Days**
---@param days int
---@return double seconds
local function getSecondsFromDays(days)
    return days * SECOND_IN_DAY
end

--- **Get Days From Seconds**
---@param seconds double
---@return int days
local function getDaysFromSeconds(seconds)
    return seconds / SECOND_IN_DAY
end

--- **Get Star Time**
--- - Format date: Fri Jul 09 09:43:41 CEST 1993
---@return double seconds
local function getStarTime()
    -- The date retrieved is 12 hours behind the digital clock in game, I added 12 hours
    ---@type string
    local date = tostring( getGameTime():getCalender():getTime() )

    ---@type int
    local dataAdjustment =  extractDate(date) + (SECOND_IN_DAY/2)
    return dataAdjustment
end

--- **Set Waiting Days**
---@param waitingDays int
---@return void
function ActivityCalendar.setWaitingOfDays(waitingDays)
    expectedDateInSecond = getStarTime() + getSecondsFromDays(waitingDays)
end

--- **Set Expected Date In Seconds**
---@param expectedDate double
---@return void
function ActivityCalendar.setExpectedDateInSecond(expectedDate)
    expectedDateInSecond = expectedDate
end

--- **Get Expected Date In Seconds**
---@return double expectedDate
function ActivityCalendar.getExpectedDateInSecond()
    return expectedDateInSecond
end

--- **Is Expected Date**
---@return boolean
function ActivityCalendar.isExpectedDate()
    --- **Check if expectedDateInSecond is nil then setWaitingOfDays**
    if not expectedDateInSecond then
        ActivityCalendar.setWaitingOfDays(1)
    end

    --- **Check if the date is correct**
    if  getStarTime() >= ActivityCalendar.getExpectedDateInSecond() then
        return true
    end

    return false
end

return ActivityCalendar