---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/10/23 09:47
---

local InventoryItemPZ = {}

local errHandler = require("lib/ErrHandler")

--- **Remove item**
---@param character IsoGameCharacter
---@param item InventoryItem
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - InventoryItem : zombie.inventory.InventoryItem
--- - ItemContainer : zombie.inventory.ItemContainer
function InventoryItemPZ.removeItem(character, item)
    if not character then
        errHandler.errMsg("InventoryItemPZ.removeItem(character, item)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    elseif not item then
        errHandler.errMsg("InventoryItemPZ.removeItem(character, item)",
                "Item " .. errHandler.err.IS_NULL)
        return nil
    end

    character:getContainer():Remove(item)
end

return InventoryItemPZ