---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 10/05/23 15:11
---

---@class ModDataX

local modDataX = {}

---Save ModData
---@param nameFile String
---@param values string or table
function modDataX.saveModData(modData, values)
    if not modData or not values then
        return nil
    end

    if type(values) ~= "table" then
        local conversionTotable = {}
        table.insert(conversionTotable, values)
        values = {}
        values = conversionTotable
        conversionTotable = nil
    end

    local lines = {}

    for i, v in pairs(values) do
        lines[i] = v
        ModData.add(modData, lines)
    end
end

---Read ModData
---@param nameFile String
---@return table
function modDataX.readModData(modData)
    if not modData then
        return nil
    end

    local lines = {}
    lines = ModData.get(modData)

    if #lines >= 2 then
        return lines
    else
        local conversionTotable ={}

        for _, v in pairs(lines) do
            table.insert(conversionTotable, v)
        end
        return conversionTotable
    end
end

---Is modData Exists
---@param nameFile String
--- - ModData : zombie.world.moddata.ModDa
function modDataX.isExists(modData)
    if not modData then
        return nil
    end

    return ModData.exists(modData)
end

--- Remove modData
---@param nameFile String
--- - ModData : zombie.world.moddata.ModDa
function modDataX.remove(modData)
    if not modData then
        return nil
    end

    ModData.remove(modData)
end

return modDataX