---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 10/05/23 15:11
---

---@class ModDataManager

local modDataManager = {}

---Save ModData
---@param nameFile String
---@param values string or table
function modDataManager.save(nameFile, values)
    if not nameFile or not values then
        return nil
    end

    if type(values) ~= "table" then
        local conversionTotable = {}
        table.insert(conversionTotable, values)
        values = {}
        values = conversionTotable
        conversionTotable = nil
    end

    local lines = {}

    for i, v in pairs(values) do
        lines[i] = v
        ModData.add(nameFile, lines)
    end
end

---Read ModData
---@param nameFile String
---@return table
function modDataManager.read(nameFile)
    if not nameFile then
        return nil
    end

    local lines = {}
    lines = ModData.get(nameFile)

    if #lines >= 2 then
        return lines
    else
        local conversionTotable ={}

        for _, v in pairs(lines) do
            table.insert(conversionTotable, v)
        end

        return conversionTotable
    end
end

---Is modData Exists
---@param nameFile String
--- - ModData : zombie.world.moddata.ModDa
function modDataManager.isExists(nameFile)
    if not nameFile then
        return nil
    end

    return ModData.exists(nameFile)
end

--- Remove modData
---@param nameFile String
--- - ModData : zombie.world.moddata.ModDa
function modDataManager.remove(nameFile)
    if not nameFile then
        return nil
    end

    ModData.remove(nameFile)
end

return modDataManager