---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 16/03/23 22:32
---

---@class PerkDetailsObj

require("lib/BaseObject")
PerkDetailsObj = BaseObject:derive("PerkDetailsObj")

--- **Create a new PerkDetailsObj**
function PerkDetailsObj:new()
    local o =  {}
    setmetatable(o, self)
    self.__index = self
    o.XPBoost = ""
    o.currentLevel = ""
    o.flag = false
    o.idGroup = ""
    o.maxLevel = ""
    o.minLevel = ""
    o.multiplier = ""
    o.perk = ""
    o.xp = ""
    return o
end

--- **Add Perk Details**
---@param perk PerkFactory.Perk
---@param currentLevel int
---@param xp float
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function PerkDetailsObj:addPerkDetails(perk, currentLevel, xp)
    self.perk = perk
    self.currentLevel = currentLevel
    self.xp = xp
end

--- **Set Minimum Level**
---@param minLevel int
---@return void
function PerkDetailsObj:setMinLevel(minLevel)
    self.minLevel = minLevel
end

--- **Get Minimum Level**
---@return int minLevel
function PerkDetailsObj:getMinLevel()
    return self.minLevel
end

--- **Set level**
---@param currentLevel int
---@return void
function PerkDetailsObj:setCurrentLevel(currentLevel)
    self.currentLevel = currentLevel
end

--- **Get Level**
---@return int Level
function PerkDetailsObj:getCurrentLevel()
    return self.currentLevel
end

--- **Set Maximum Level**
---@param maxLevel int
---@return void
function PerkDetailsObj:setMaxLevel(maxLevel)
    self.maxLevel = maxLevel
end

--- **Get Maximum Level**
---@return int maxLevel
function PerkDetailsObj:getMaxLevel()
    return self.maxLevel
end

--- **Set Level**
---@param xp float
---@return void
function PerkDetailsObj:setXp(xp)
    self.xp = xp
end

--- **Get XP**
---@return float xp
function PerkDetailsObj:getXp()
    return self.xp
end

--- **Set perk**
---@param perk PerkFactory.Perk
---@return void
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk.Perk
function PerkDetailsObj:setPerk(perk)
    self.perk = perk
end

--- **Get Perk**
---@return PerkFactory.Perk perk
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactor
function PerkDetailsObj:getPerk()
    return self.perk
end

--- **Set Boost**
---@param XPBoost int
---@return void
function PerkDetailsObj:setXPBoost(XPBoost)
    self.XPBoost = XPBoost
end

--- **Get Boost**
---@return int XPBoost
function PerkDetailsObj:getXPBoost()
    return self.XPBoost
end

--- **Set Multiplier**
---@param multiplier double
---@return void
function PerkDetailsObj:setMultiplier(multiplier)
    self.multiplier = multiplier
end

--- **Get Multiplier**
---@return double multiplier
function PerkDetailsObj:getMultiplier()
    return self.multiplier
end

--- **Set Flag**
---@param flag boolean
---@return void
function PerkDetailsObj:setFlag(flag)
    self.flag = flag
end

--- **Get Flag**
---@return boolean flag
function PerkDetailsObj:getFlag()
    return self.flag
end

--- **Set idGroup**
---@param idGroup string
---@return void
function PerkDetailsObj:setIdGroup(idGroup)
    self.idGroup = idGroup
end

--- **Get idGroup**
---@return string idGroup
function PerkDetailsObj:getIdGroup()
    return self.idGroup
end
