---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 16/03/23 22:32
---

---@class PerkDetailsObj

require("lib/BaseObject")
PerkDetailsObj = BaseObject:derive("PerkDetailsObj")

function PerkDetailsObj:new()
    local o =  {}
    setmetatable(o, self)
    self.__index = self
    o.perk = ""
    o.level = ""
    o.xp = ""
    o.boostLevel = ""
    o.multiplier = ""
    o.flag = false
    return o
end

---Add Perk Details
---@param perk PerkFactory.Perk
---@param level int
---@param xp float
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactor
function PerkDetailsObj:addPerkDetails(perk, level, xp)
    self.perk = perk
    self.level = level
    self.xp = xp
end

---Set Flag
---@param flag boolean
function PerkDetailsObj:setFlag(flag)
    self.flag = flag
end

---Get Flag
---@return boolean
function PerkDetailsObj:getFlag()
    return self.flag
end

---Set level
---@param level int
function PerkDetailsObj:setLevel(level)
    self.level = level
end

--- Get Level
---@return int Level
function PerkDetailsObj:getLevel()
    return self.level
end

---Set Level
---@param xp float
function PerkDetailsObj:setXp(xp)
    self.xp = xp
end

---Get XP
---@return float xp
function PerkDetailsObj:getXp()
    return self.xp
end

---Set perk
---@param perk PerkFactory.Perk
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactor
function PerkDetailsObj:setPerk(perk)
    self.perk = perk
end

---Get Perk
---@return PerkFactory.Perk perk
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactor
function PerkDetailsObj:getPerk()
    return self.perk
end

---Set Boost
---@param boostLevel int
function PerkDetailsObj:setBoostLevel(boostLevel)
    self.boostLevel = boostLevel
end

---Get Boost
---@return int boostLevel
function PerkDetailsObj:getBoostLevel()
    return self.boostLevel
end

---Set Multiplier
---@param multiplier double
function PerkDetailsObj:setMultiplier(multiplier)
    self.multiplier = multiplier
end

---Get Multiplier
---@return double multiplier
function PerkDetailsObj:getMultiplier()
    return self.multiplier
end




