---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 27/03/23 09:38
---

---@class DbgLeleLib

---@param displayName string
---@param perk
---@param level
function DBG_displayPerk(displayName, perk, level, xp)
    local dbg1 = perk
    local dbg2 = level
    local dbg3 = xp
    print("--------------------------------")
    print("DBG_displayPerk " .. displayName .. " - "
            .. tostring(perk) .. " - "
            .. tostring(level) .. " - "
            .. tostring(xp))
    print("--------------------------------")
    local dbg
end

---@param displayName string
---@param perk_ PerkFactory.Perk
---@param perk PerkFactory.Perk
---@param level int
function DBG_GetCheckPerk(displayName, perk_, perk, level )
    -- Perks.Maintenance
    local dbg1
    local dbg2
    local dbg3 = perk
    local dbg4 = perk_
    local dbg5 = level
    if perk_ == perk then
        dbg1 = perk_
        dbg2 = level
        print("--------------------------------")
        print("dbg_displayName ".. displayName ..
                " - " .. tostring(perk) .. " - " .. tostring(level))
        print("--------------------------------")

        local dbg
    end

    local dbg
end

---@param displayName string
---@param table
function DBG_displayListPerks(displayName, perks_list)
    print("--------------------------------")
    for i, v in pairs(perks_list) do
        print("dbg_displayName " ..
                displayName .. "   i " ..
                tostring(i) .. " >>>>> " ..
                tostring(v.perk) .. " - " ..
                tostring(v.level))
        -- DBG_GetCheckPerk("DBG_GetCheckPerk", v.perk_, v.perk, _ )
    end
    print("--------------------------------")
end