---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/02/23 20:48
---

local AbilityObj = {}
local MetaAbility = {}
MetaAbility.__Index = AbilityObj

local instance

---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function AbilityObj.new(perk, level, xp)
    instance = setmetatable({}, MetaAbility)
    instance.perk = perk
    instance.level = level
    instance.xp = xp
    return instance
end

--- Get Level
---@return int Level
function AbilityObj.getLevel()
    return instance.level
end

---Get XP
---@return float xp
function AbilityObj.getXp()
    return instance.xp
end
---Get Perk
---@return PerkFactory.Perk perk
function AbilityObj.getPerk()
    return instance.perk
end

return AbilityObj