---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/02/23 14:46
--- non sono sicuro dei local, sembra funzionare
--- return CharacterOOP l'ho aggiunto io e restuisce i metodi
---
local AbilityObj = require("objects/AbilityObj")

local CharacterObj = {}
local MetaCharacter = {}
MetaCharacter.__index = CharacterObj
local abilitys = {}

local instance

---Init Object
function initCharacterObj()
    if not instance then
        instance = setmetatable({}, MetaCharacter)
    end
end

---Create Character
---@param profession string
function CharacterObj.createCharacter(profession)
    initCharacterObj()
    instance.profession = profession

    -- reset table
    abilitys = {}
    return instance
end

---Current Character
---@param profession string
---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function CharacterObj.currentCharacter(profession, perk, level, xp)
    initCharacterObj()
    instance.profession = profession
    AbilityObj.new(perk, level, xp)
    return instance
end

---Add Ability
---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function CharacterObj.addAbility(perk, level, xp)
    table.insert(abilitys, AbilityObj.new(perk, level, xp))
end

---Get Abilitys
---@return table perk, level, xp
function CharacterObj.getAbilitys()
    return abilitys
end

---Get Abilitys
---@return AbilityObj perk, level, xp
function CharacterObj.getAbility()
    return AbilityObj
end

---Set Profession
---@param profession string
function CharacterObj.setProfession(profession)
    instance.profession = profession
end

---Get Profession
---return string profession
function CharacterObj.getProfession()
    return instance.profession
end

---Set name
---@param name string
function CharacterObj.setName(name)
    instance.name = name
end

---Get name
---@return string name
function CharacterObj.getName()
    return instance.name
end

---Set name
---@param surname string
function CharacterObj.setSurname(surname)
    instance.surname = surname
end

---Get surname
---@return string surname
function CharacterObj.getSurname()
    return instance.surname
end

return CharacterObj