---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/02/23 14:46
--- non sono sicuro dei local, sembra funzionare
--- return CharacterOOP l'ho aggiunto io e restuisce i metodi
---

---@class CharacterObj

local PerkDetailsObj = require("objects/PerkDetailsObj")

-- TODO al capo non piacciano, sistemare gli oggetti come da sue specifiche
local CharacterObj = {}
local MetaCharacter = {}
MetaCharacter.__index = CharacterObj
local perkDetails_LIST = {}

local instance

---Init Object
function initCharacterObj()
    if not instance then
        instance = setmetatable({}, MetaCharacter)
    end
end

---Create Character
---@param profession string
function CharacterObj.createCharacter(profession)
    initCharacterObj()
    instance.profession = profession

    -- reset table
    perkDetails_LIST = {}
    return instance
end

---Current Character
---@param profession string
---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function CharacterObj.currentCharacter(profession, perk, level, xp)
    initCharacterObj()
    instance.profession = profession
    PerkDetailsObj.addPerkDetails(perk, level, xp)
    return instance
end

---Add Perk Details ( list )
---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function CharacterObj.addPerkDetails(perk, level, xp)
    table.insert(perkDetails_LIST, PerkDetailsObj.addPerkDetails(perk, level, xp))
end

---Remove Perk Details ( list )
---@param value int
function CharacterObj.removePerkDetails(value)
    table.remove(perkDetails_LIST, value)
end

---Get Perk Details
---@return table perk, level, xp
function CharacterObj.getPerkDetails()
    return perkDetails_LIST
end

---Get object PerkDetailsObj
---@return PerkDetailsObj
function CharacterObj.getPerkDetailsObj()
    return PerkDetailsObj
end

---Set Profession
---@param profession string
function CharacterObj.setProfession(profession)
    instance.profession = profession
end

---Get Profession
---@return string profession
function CharacterObj.getProfession()
    return instance.profession
end

---Set name
---@param name string
function CharacterObj.setName(name)
    instance.name = name
end

---Get name
---@return string name
function CharacterObj.getName()
    return instance.name
end

---Set name
---@param surname string
function CharacterObj.setSurname(surname)
    instance.surname = surname
end

---Get surname
---@return string surname
function CharacterObj.getSurname()
    return instance.surname
end

return CharacterObj