---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/02/23 20:48
---
---@class PerkDetailsObj

-- TODO al capo non piacciano, sistemare gli oggetti come da sue specifiche
local PerkDetailsObj = {}
local MetaPerkDetailsObj = {}
MetaPerkDetailsObj.__Index = PerkDetailsObj

local instance

---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function PerkDetailsObj.addPerkDetails(perk, level, xp)
    instance = setmetatable({}, MetaPerkDetailsObj)
    instance.perk = perk
    instance.level = level
    instance.xp = xp
    return instance
end

---Set Flag
---@param flag
function PerkDetailsObj.setFlag(flag)
    instance.flag = flag
end

---Get Flag
---@return boolean
function PerkDetailsObj.getFlag()
    return instance.flag
end

--- Get Level
---@return int Level
function PerkDetailsObj.getLevel()
    return instance.level
end

---Get XP
---@return float xp
function PerkDetailsObj.getXp()
    return instance.xp
end
---Get Perk
---@return PerkFactory.Perk perk
function PerkDetailsObj.getPerk()
    return instance.perk
end

return PerkDetailsObj