---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 16/03/23 22:32
---

---@class PerkDetailsObj

PerkDetailsObj = {
    perk = "",
    level = 0,
    xp = 0.0,
    flag = false
}

function PerkDetailsObj:newObject(t)
    t = t or {}
    setmetatable(t, self)
    self.__index = self
    return t
end

---Add Perk Details
---@param perk PerkFactory.Perk
---@param level int
---@param xp float
function PerkDetailsObj:addPerkDetails(perk, level, xp)
    self.perk = perk
    self.level = level
    self.xp = xp
end

---Set Flag
---@param flag
function PerkDetailsObj:setFlag(flag)
    self.flag = flag
end

---Get Flag
---@return boolean
function PerkDetailsObj:getFlag()
    return self.flag
end

---Set level
---@param level int
function PerkDetailsObj:setLevel(level)
    self.level = level
end

--- Get Level
---@return int Level
function PerkDetailsObj:getLevel()
    return self.level
end

---Set Level
---@param xp float
function PerkDetailsObj:setXp(xp)
    self.xp = xp
end

---Get XP
---@return float xp
function PerkDetailsObj:getXp()
    return self.xp
end

---Set perk
---@param perk PerkFactory.Perk
function PerkDetailsObj:setPerk(perk)
    self.perk = perk
end

---Get Perk
---@return PerkFactory.Perk perk
function PerkDetailsObj:getPerk()
    return self.perk
end






