---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/10/23 16:21
---

---@class BlockLevel

local characterPz = require("lib/CharacterPZ")
local errHandler = require("lib/ErrHandler")
local perkFactoryPZ = require("lib/PerkFactoryPZ")

local BlockLevel = {}

--- **Block Level**
---@param character IsoGameCharacter
---@param currentPerkLevel int
---@param perk PerkFactory
---@param maxLevel int
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory : zombie.characters.skills.PerkFactory
function BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)
    if not character then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    if not perk then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    if not currentPerkLevel then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " currentPerkLevel " .. errHandler.err.IS_NULL)
        return nil
    end

    if not maxLevel then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " maxLevel " .. errHandler.err.IS_NULL)
        return nil
    end

    local convertLevelToXp_ = 0.0

    if currentPerkLevel >= maxLevel then
        ---@type int
        for level_ = 1, maxLevel do
            convertLevelToXp_ = convertLevelToXp_ +
                    perkFactoryPZ.convertLevelToXp(perk, level_)
        end
    end

    local totalXp = ( convertLevelToXp_ -
            characterPz.getXp(character, perk))

    if totalXp == 0 then
        return
    end

    characterPz.addXP_PZ(character, perk, totalXp, false, false, true)
end

---Calculate Block Level
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param CreateCharacterMaxSkillObj CharacterBaseObj
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)
    if not character then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    if not CreateCharacterMaxSkillObj then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)",
                " CreateCharacterMaxSkillObj " .. errHandler.err.IS_NULL)
        return nil
    end

    if not perk then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    local currentPerkLevel = characterPz.getPerkLevel_PZ(character, perk)
    local maxLevel = characterPz.EnumNumbers.TEN

    for _, v in pairs(CreateCharacterMaxSkillObj:getPerkDetails()) do
        if v:getPerk() == perk then
            if v:getCurrentLevel() == maxLevel then
                return
            end

            if currentPerkLevel >= v:getMaxLevel() then
                BlockLevel.blockLevel(character, v:getPerk(), currentPerkLevel, v:getMaxLevel())
            end
        end
    end
end

--- **Check Level Max**
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param CreateCharacterMaxSkillObj CharacterBaseObj
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)
    if not character then
        errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    if not perk then
        errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    if not CreateCharacterMaxSkillObj then
        errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
                " CreateCharacterMaxSkillObj " .. errHandler.err.IS_NULL)
        return nil
    end

    BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)
end

return BlockLevel