---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 26/10/23 11:56
---

---@class CharacterMaxSkill

require("lib/CharacterBaseObj")
require("lib/PerkDetailsObj")

local characterCreation = require("CharacterCreation")
local characterPz = require("lib/CharacterPZ")
local errHandler = require("lib/ErrHandler")
local group = require("Group")

local CharacterMaxSkill = {}

--- **Get Rule Perk max Level**
---@param levelCurrentPerk int
---@return int
function CharacterMaxSkill.getRulePerk(levelCurrentPerk)
    -- **Check if levelCurrentPerk is null**
    if not levelCurrentPerk then
        errHandler.errMsg("CharacterMaxSkill.getCharacterMaxLevelPerkObj(levelCurrentPerk)",
                "levelCurrentPerk " .. errHandler.err.IS_NULL)
        return nil
    end

    ---@type int
    local result

    if levelCurrentPerk == characterPz.EnumNumbers.ZERO then -- 0
        result = characterPz.EnumNumbers.FOUR -- max 4
    elseif levelCurrentPerk == characterPz.EnumNumbers.ONE then -- 1
        result = characterPz.EnumNumbers.SIX -- max levelPerk 6
    elseif levelCurrentPerk == characterPz.EnumNumbers.TWO then -- 2
        result = characterPz.EnumNumbers.EIGHT -- max levelPerk 8
    elseif levelCurrentPerk >= characterPz.EnumNumbers.THREE then -- 3
        result = characterPz.EnumNumbers.TEN -- max levelPerk 10
    end

    return result
end

--- **Get Rule Combat max Level**
---@param combatCurrentPerk int
---@return int Combat Max Level
function CharacterMaxSkill.getRuleCombat(combatCurrentPerk)
    -- **Check if combatCurrentPerk is null**
    if not combatCurrentPerk then
        errHandler.errMsg("CharacterMaxSkill.getCharacterMaxLevelCombatObj(combatCurrentPerk)",
                "combatCurrentPerk " .. errHandler.err.IS_NULL)
        return nil
    end

    ---@type int
    local result

    if combatCurrentPerk == characterPz.EnumNumbers.ZERO then -- 0
        result = characterPz.EnumNumbers.FOUR -- max levelPerk 4
    elseif combatCurrentPerk == characterPz.EnumNumbers.ONE then -- 1
        result = characterPz.EnumNumbers.SEVEN -- max levelPerk 7
    elseif combatCurrentPerk >= characterPz.EnumNumbers.TWO then -- 2
        result = characterPz.EnumNumbers.TEN -- max levelPerk 10
    end

    return result
end

--- **Get Rule Profession max Level**
---@param levelCurrentPerk int
---@return int
function CharacterMaxSkill.getRuleProfession(levelCurrentPerk)
    -- **Check if levelCurrentPerk is null**
    if not levelCurrentPerk then
        errHandler.errMsg("CharacterMaxSkill.getCharacterProfessionMaxLevel(levelCurrentPerk)",
                "levelCurrentPerk " .. errHandler.err.IS_NULL)
        return nil
    end

    return CharacterMaxSkill.getRulePerk(levelCurrentPerk)
end

--- Get Create Character Max Skill
---@param character IsoGameCharacter
---@return CharacterBaseObj getPerkDetails() PerkFactory.Perk perk, int currentlevel, int maxlevel, string grou
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function CharacterMaxSkill.getCreateMaxSkill(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("CharacterMaxSkill.getCreateMaxSkill(character)",
                errHandler.err.IS_NULL_CHARACTER)
        return nil
    end

    -- @type CharacterBaseObj
    local CharacterBaseObj01 = CharacterBaseObj:new()

    ---@type table - PerkFactory.Perk perk, int currentlevel, int maxlevel, string group
    local characterCreationX = characterCreation.getCharacterCreation(character)

    for perk, value in pairs(characterCreationX) do
        local PerkDetailsObj01 = PerkDetailsObj:new()

        --- **Set Maximum Level for No limits group**
        if value.group == group.NO_LIMITS  then
            PerkDetailsObj01:setMaxLevel(characterPz.EnumNumbers.TEN)
        end

        --- **Set Maximum Level for Profession group**
        if value.group == group.PROFESSION then
            PerkDetailsObj01:setMaxLevel(CharacterMaxSkill.getRuleProfession(value.currentLevel))
        end

        --- **Feature disabled, check CharacterCreation**
        ----- **Set Maximum Level for Combat group**
        --if value.group == group.COMBAT then
        --    PerkDetailsObj01:setMaxLevel(CharacterMaxSkill.getRuleCombat(0))
        --end

        --- **Set Maximum Level for Generic group**
        if value.group == group.GENERIC then
            PerkDetailsObj01:setMaxLevel(CharacterMaxSkill.getRulePerk(0))
        end

        --- **Set Perk Details**
        PerkDetailsObj01:setPerk(perk)
        --- **Set Current XP**
        PerkDetailsObj01:setXp(characterPz.getXp(character, perk))
        --- **Set Current Level**
        PerkDetailsObj01:setCurrentLevel(value.currentLevel)
        --- **Save Perk Details**
        CharacterBaseObj01:savePerkDetails(PerkDetailsObj01)
    end

    return CharacterBaseObj01
end

return CharacterMaxSkill