---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 25/10/23 20:18
---

---@class Group

local Group = {
    ---@type string
    NO_LIMITS = "No limits",
    ---@type string
    PROFESSION = "Profession",
    ---@type string
    GENERIC = "Generic",
    ---@type string
    COMBAT = "Combat"
}

return Group