---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/02/23 19:11
--- function ISSkillProgressBar:renderPerkRect()
--- ISSkillProgressBar:updateTooltip(lvlSelected)
-- -----------------------------------------------------------------

---@class SkillLimiter

local SkillLimiter = {}

local debugDiagnostics = require("lib/DebugDiagnostics")
local blockLevel = require("BlockLevel")
local characterMaxSkill = require("CharacterMaxSkill")
local characterLib = require("CharacterLib")
local modDataManager = require("lib/ModDataManager")
-- local characterBaseObj = require("lib/CharacterBaseObj")
require("lib/CharacterBaseObj")

---@type CharacterBaseObj
local CreateCharacterMaxSkillObj = CharacterBaseObj:new()

-- Create Character Max Skill and create ModData
---@return CharacterBaseObj
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function SkillLimiter.initCharacter()
    ---
    local characterMaxSkillModData = "characterMaxSkill"

    ---@type table
    local characterMaxSkillTable -- = {}

    if modDataManager.isExists(characterMaxSkillModData) then
        characterMaxSkillTable =
            modDataManager.read(characterMaxSkillModData)

        CreateCharacterMaxSkillObj =
            characterLib.decodePerkDetails(characterMaxSkillTable)
    else
        CreateCharacterMaxSkillObj =
            characterMaxSkill.getCreateCharacterMaxSkill( debugDiagnostics.characterUpdate() )

        characterMaxSkillTable =
            characterLib.encodePerkDetails(CreateCharacterMaxSkillObj)

        modDataManager.save(characterMaxSkillModData, characterMaxSkillTable )
    end

    return CreateCharacterMaxSkillObj
end

---Delete modData when character is death -
---Triggered when a character or zombie is killed
---@param character IsoGameCharacter
local function OnCharacterDeath(character)
    if getPlayer():isDead() then
        print("ucciso umano")
        local characterMaxSkillModData = "characterMaxSkill"
        modDataManager.remove(characterMaxSkillModData)
    end
end

---Check Level Max
---Triggered when a player gains XP.
local function AddXP(character, perk, level)
    blockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)
end

---Init Character -
---Triggered after the start of a new game, and after a saved game has been loaded.
local function OnGameStart()
    CreateCharacterMaxSkillObj = SkillLimiter.initCharacter()
end

---Init Character -
---Triggered when a player is being created.
local function OnCreatePlayer(playerIndex, player)
    CreateCharacterMaxSkillObj = SkillLimiter.initCharacter()
end

--Events.OnCharacterDeath.Add(OnCharacterDeath)
--Events.AddXP.Add(AddXP)
--Events.OnGameStart.Add(OnGameStart)
--Events.OnCreatePlayer.Add(OnCreatePlayer)

return SkillLimiter