---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/02/23 19:11
--- function ISSkillProgressBar:renderPerkRect()
--- ISSkillProgressBar:updateTooltip(lvlSelected)
-- -----------------------------------------------------------------

---@class SkillLimiter

local modDataX = require("lib/ModDataX")
local characterLib = require("CharacterLib")

local CreateCharacterMaxSkillObj = CharacterBaseObj:new()

-- Create Character Max Skill and create ModData
---@return CharacterBaseObj
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function initCharacter()
    local characterMaxSkillModData = "characterMaxSkill"
    local characterMaxSkillTable = {}

    if modDataX.isExists(characterMaxSkillModData) then
        characterMaxSkillTable =
            modDataX.readModData(characterMaxSkillModData)

        CreateCharacterMaxSkillObj =
            characterLib.decodePerkDetails(characterMaxSkillTable)
    else
        CreateCharacterMaxSkillObj =
            getCreateCharacterMaxSkill( getPlayer() )

        characterMaxSkillTable =
            characterLib.encodePerkDetails(CreateCharacterMaxSkillObj)

        modDataX.saveModData(characterMaxSkillModData, characterMaxSkillTable )
    end

    return CreateCharacterMaxSkillObj
end

---Delete modData when character is death -
---Triggered when a character or zombie is killed
---@param character IsoGameCharacter
local function OnCharacterDeath(character)
    if getPlayer():isDead() then
        print("ucciso umano")
        local characterMaxSkillModData = "characterMaxSkill"
        modDataX.remove(characterMaxSkillModData)
    end
end

---Check Level Max
---Triggered when a player gains XP.
local function AddXP(character, perk, level)
    checkLevelMax(character, perk, CreateCharacterMaxSkillObj)
end

---Init Character -
---Triggered after the start of a new game, and after a saved game has been loaded.
local function OnGameStart()
    initCharacter()
end

---Init Character -
---Triggered when a player is being created.
local function OnCreatePlayer(playerIndex, player)
    initCharacter()
end

Events.OnCharacterDeath.Add(OnCharacterDeath)
Events.AddXP.Add(AddXP)
Events.OnGameStart.Add(OnGameStart)
Events.OnCreatePlayer.Add(OnCreatePlayer)
