---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 23/03/23 10:33
---

---@class BlockLevel

---@param character IsoGameCharacter
---@param perk PerkFactory
---@param maxLevel int
---@param CharacterTableX CharacterTableX
local function blockLevel(character, perk, maxLevel)
    local convertLevelToXp_ = 0.0

    for level_ = 1, maxLevel do
        convertLevelToXp_ = convertLevelToXp_ + convertLevelToXp(perk, level_)
    end

    local totalXp = ( convertLevelToXp_ -
            getXpPerk_PZ( character, perk ) ) * 2

    if totalXp == 0 then
        return
    end

    addXP_PZ(character, perk, totalXp )
end

---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param tables --- perk level
local function calculateBlockLevel(character, perk, tables)
    local perkLevel = getPerkLevel_PZ(character, perk)

    for _, v in pairs(tables) do
        if v.perk == perk then
            if v.level >= perkLevel then
                blockLevel(character, v.perk, v.level)
            end
        end
    end
end

---Check Level Max
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param _ --- unused
function checkLevelMax(character, perk, _)
    if not character or not perk then
        return nil
    end

    local characterMaxLevelCombats, characterMaxLevelPerks = {}

    characterMaxLevelCombats, characterMaxLevelPerks =
        getCreateCharacterMaxSkill(character)

    calculateBlockLevel(character, perk, characterMaxLevelCombats)
    calculateBlockLevel(character, perk, characterMaxLevelPerks)
end
